org.gradle.jvmargs=-Xmx5G
org.gradle.daemon=false
systemProp.net.minecraftforge.gradle.repo.recompile.fork=true
systemProp.net.minecraftforge.gradle.repo.recompile.fork.args=-Xmx5G
systemProp.net.minecraftforge.gradle.repo.attach=false
minecraft_version=1.21.11
minecraft_version_range=[1.21.11,1.22)
forge_version=61.0.10
forge_version_range=[61,)
loader_version_range=[61,)
mapping_channel=official
mapping_version=1.21.11

mod_id=fcstonefences
mod_name=FC's Stone Fences
mod_license=GNU-GPLv3.0
mod_version=1.1.0
mod_group_id=com.fleece.fcstonefences
mod_authors=FleeceComrade
mod_description=This mod adds 264 fences that have stone posts and wooden crossbeams.