modLoader="javafml"
loaderVersion="[43,)"
license="GNU-GPLv3.0"

[[mods]]
modId="fcstonefences"
version="1.19.2-1.1.0"
displayName="FC's Stone Fences"
logoFile="fcstonefenceslogo.png"
credits="Thanks Bro"
authors="FleeceComrade"

description="This mod adds 216 fences that have stone posts and wooden crossbeams."

[[dependencies.fcstonefences]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.fcstonefences]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"
